### ISSUE TITLE
Penrose inverse

### ISSUE THREAD

**Issue by jdbancal** [gem-library/gem#19]
The "Moore–Penrose inverse" (pinv function) is not available.

**Comment by jdbancal** [comment]
Actually, Matlab's implementation of pinv works out of the box... what is the problem exactly?
Any example that fails?

**Comment by wellisongomes** [comment]
When I try to use pinv in MATLAB R2018a, I get the following error:
"Error using gem/subsasgn (line 83)
Indices out of bound in gem::subsasgn

Error in pinv (line 24)
V(:,r1:end) = [];"

The code works when I use inv() instead. However, sometimes my matrices are not square and some ill-conditioning also occurs.

**Comment by jdbancal** [comment]
Awesome, thanks for these precisions! I think the problem lies in `subsasgn`. Namely, if
```
>> V = rand(3)

V =

    0.7922    0.0357    0.6787
    0.9595    0.8491    0.7577
    0.6557    0.9340    0.7431
```
is a `3x3` matrix, Matlab refuses the following syntax:
```
>> V(:,4)
Index in position 2 exceeds array bounds (must not exceed 3).
```
because we refer to a dimension larger than contained in `V`, i.e. `4>3`.

However, Matlab still accepts the following syntaxes:
```
>> V(:,4:end)

ans =

  3×0 empty double matrix

>> V(:,4:end)=[]

V =

    0.7922    0.0357    0.6787
    0.9595    0.8491    0.7577
    0.6557    0.9340    0.7431

>> V(:,3)=[]

V =

    0.7922    0.0357
    0.9595    0.8491
    0.6557    0.9340
```
Currently, `gem` rejects these syntaxes because they involve invalid indices and/or the sizes don't match. `gem::subsasgn` should be a bit more flexible here.

**Comment by jdbancal** [comment]
The `subsasgn` part is now fixed in 60585d6, but one more problem arises: `times` multiplications with the `.*` operator should be allowed when the matrices are not of the same dimension, in the case where the mismatched dimension is 1 for one of the two arguments... Fixing this should make the native `pinv` function work.

**Comment by jdbancal** [comment]
This issue should be fixed in the latest release https://github.com/gem-library/gem/releases/tag/v2.0.2

**Comment by wellisongomes** [comment]
Dear Jean-Daniel,

Thank you very much! Sorry it took me so long to answer. I will try to use
the latest release as soon as possible.

Best regards,

Wellison Gomes

**Comment by wellisongomes** [comment]
Thank you very much!
